# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "annees", :id => false, :force => true do |t|
    t.column "annee", :integer
  end

  create_table "armstransfers", :id => false, :force => true do |t|
    t.column "ordre", :integer
    t.column "licensed", :integer
    t.column "supplier", :string, :limit => 40
    t.column "recipient", :string, :limit => 40
    t.column "description", :string, :limit => 40
    t.column "year_order", :integer
    t.column "year_deliv1", :integer
    t.column "year_deliv2", :integer
  end

# Could not dump table "at_map" because of following StandardError
#   Unknown type 'geometry' for column 'segment'

# Could not dump table "buildings" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "conflits", :force => true do |t|
    t.column "primkey", :integer
    t.column "subid", :integer
    t.column "location", :text
    t.column "side_a", :text
    t.column "side_b", :text
    t.column "incompatibility", :integer
    t.column "territory", :text
    t.column "year", :integer
    t.column "intensity", :integer
    t.column "type", :integer
    t.column "startdate", :datetime
    t.column "startprecision", :integer
    t.column "startdate2", :datetime
    t.column "startprecision2", :integer
    t.column "cow_a", :text
    t.column "cow_b", :text
    t.column "cow_location", :text
    t.column "region", :integer
    t.column "lat", :float
    t.column "lon", :float
    t.column "radius", :integer
    t.column "version", :integer
    t.column "cercle", :string, :limit => nil
  end

# Could not dump table "conflits_ext" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "conflitsexts", :force => true do |t|
    t.column "ltlgrd", :text
    t.column "confid", :integer
    t.column "subid", :integer
    t.column "begin", :integer
    t.column "finish", :integer
    t.column "intensity", :integer
    t.column "type_of_war", :integer
    t.column "territory", :string, :limit => nil
    t.column "side_a", :string, :limit => 128
    t.column "side_b", :string, :limit => 128
    t.column "old_id", :string, :limit => 10
  end

# Could not dump table "continents" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "corresp", :id => false, :force => true do |t|
    t.column "pays_sipri", :string, :limit => 40
    t.column "pays_world", :string, :limit => 40
  end

# Could not dump table "gaza" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "geometry_columns", :id => false, :force => true do |t|
    t.column "f_table_catalog", :string, :limit => 256, :null => false
    t.column "f_table_schema", :string, :limit => 256, :null => false
    t.column "f_table_name", :string, :limit => 256, :null => false
    t.column "f_geometry_column", :string, :limit => 256, :null => false
    t.column "coord_dimension", :integer, :null => false
    t.column "srid", :integer, :null => false
    t.column "type", :string, :limit => 30, :null => false
  end

# Could not dump table "great_roads" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "mapserver_desc", :primary_key => "ms_gid", :force => true do |t|
    t.column "ms_table", :text
    t.column "ms_libelle", :text
    t.column "ms_name", :text
    t.column "ms_labelitem", :text
    t.column "ms_color", :text
    t.column "ms_outlinecolor", :text
    t.column "ms_symbol", :text
  end

# Could not dump table "parcs" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

# Could not dump table "personnes" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "pga_diagrams", :id => false, :force => true do |t|
    t.column "diagramname", :string, :limit => 64, :null => false
    t.column "diagramtables", :text
    t.column "diagramlinks", :text
  end

  create_table "pga_forms", :id => false, :force => true do |t|
    t.column "formname", :string, :limit => 64, :null => false
    t.column "formsource", :text
  end

  create_table "pga_graphs", :id => false, :force => true do |t|
    t.column "graphname", :string, :limit => 64, :null => false
    t.column "graphsource", :text
    t.column "graphcode", :text
  end

  create_table "pga_images", :id => false, :force => true do |t|
    t.column "imagename", :string, :limit => 64, :null => false
    t.column "imagesource", :text
  end

  create_table "pga_layout", :id => false, :force => true do |t|
    t.column "tablename", :string, :limit => 64, :null => false
    t.column "nrcols", :integer
    t.column "colnames", :text
    t.column "colwidth", :text
  end

  create_table "pga_queries", :id => false, :force => true do |t|
    t.column "queryname", :string, :limit => 64, :null => false
    t.column "querytype", :string, :limit => 1
    t.column "querycommand", :text
    t.column "querytables", :text
    t.column "querylinks", :text
    t.column "queryresults", :text
    t.column "querycomments", :text
  end

  create_table "pga_reports", :id => false, :force => true do |t|
    t.column "reportname", :string, :limit => 64, :null => false
    t.column "reportsource", :text
    t.column "reportbody", :text
    t.column "reportprocs", :text
    t.column "reportoptions", :text
  end

  create_table "pga_scripts", :id => false, :force => true do |t|
    t.column "scriptname", :string, :limit => 64, :null => false
    t.column "scriptsource", :text
  end

# Could not dump table "rivers" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "sipri_world", :id => false, :force => true do |t|
    t.column "pays_sipri", :string, :limit => 40
    t.column "pays_world", :string, :limit => 40
    t.column "fips_cntry", :string, :limit => 2
  end

# Could not dump table "small_roads" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

  create_table "spatial_ref_sys", :id => false, :force => true do |t|
    t.column "srid", :integer, :null => false
    t.column "auth_name", :string, :limit => 256
    t.column "auth_srid", :integer
    t.column "srtext", :string, :limit => 2048
    t.column "proj4text", :string, :limit => 2048
  end

# Could not dump table "tmp2" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

# Could not dump table "tmp3" because of following StandardError
#   Unknown type 'geometry' for column 'points'

# Could not dump table "tmp4" because of following StandardError
#   Unknown type 'geometry' for column 'cercle'

# Could not dump table "world" because of following StandardError
#   Unknown type 'geometry' for column 'the_geom'

end
