# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 10) do

  create_table "annees", :id => false, :force => true do |t|
    t.integer "annee"
  end

  create_table "dataset_1", :force => true do |t|
    t.string  "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.decimal "var10"
    t.decimal "var11"
  end

  create_table "dataset_10", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_11", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_12", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
    t.integer "var49"
    t.integer "var50"
    t.integer "var51"
    t.integer "var52"
    t.integer "var53"
    t.integer "var54"
    t.integer "var55"
    t.integer "var56"
    t.integer "var57"
    t.integer "var58"
  end

  create_table "dataset_13", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
  end

  create_table "dataset_14", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
  end

  create_table "dataset_15", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
  end

  create_table "dataset_16", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
  end

  create_table "dataset_17", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
  end

  create_table "dataset_18", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
  end

  create_table "dataset_19", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
  end

  create_table "dataset_2", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.string  "var3"
    t.string  "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.decimal "var37"
  end

  create_table "dataset_20", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
  end

  create_table "dataset_21", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
    t.integer "var49"
  end

  create_table "dataset_22", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
    t.integer "var49"
    t.integer "var50"
  end

  create_table "dataset_23", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
  end

  create_table "dataset_24", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
    t.integer "var49"
    t.integer "var50"
    t.integer "var51"
    t.integer "var52"
    t.integer "var53"
    t.integer "var54"
    t.integer "var55"
  end

  create_table "dataset_25", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
  end

  create_table "dataset_3", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
  end

  create_table "dataset_32", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.decimal "var7"
  end

  create_table "dataset_33", :force => true do |t|
    t.string  "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.decimal "var10"
    t.decimal "var11"
  end

  create_table "dataset_34", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.decimal "var7"
  end

  create_table "dataset_35", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
    t.integer "var7"
    t.integer "var8"
    t.integer "var9"
    t.integer "var10"
    t.integer "var11"
    t.integer "var12"
    t.integer "var13"
    t.integer "var14"
    t.integer "var15"
    t.integer "var16"
    t.integer "var17"
    t.integer "var18"
    t.integer "var19"
    t.integer "var20"
    t.integer "var21"
    t.integer "var22"
    t.integer "var23"
    t.integer "var24"
    t.integer "var25"
    t.integer "var26"
    t.integer "var27"
    t.integer "var28"
    t.integer "var29"
    t.integer "var30"
    t.integer "var31"
    t.integer "var32"
    t.integer "var33"
    t.integer "var34"
    t.integer "var35"
    t.integer "var36"
    t.integer "var37"
    t.integer "var38"
    t.integer "var39"
    t.integer "var40"
    t.integer "var41"
    t.integer "var42"
    t.integer "var43"
    t.integer "var44"
    t.integer "var45"
    t.integer "var46"
    t.integer "var47"
    t.integer "var48"
    t.integer "var49"
    t.integer "var50"
    t.integer "var51"
    t.integer "var52"
    t.integer "var53"
    t.integer "var54"
    t.integer "var55"
  end

  create_table "dataset_4", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
  end

  create_table "dataset_5", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_6", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_7", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_8", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "dataset_9", :force => true do |t|
    t.integer "var1"
    t.integer "var2"
    t.integer "var3"
    t.integer "var4"
    t.integer "var5"
    t.integer "var6"
  end

  create_table "datasets", :force => true do |t|
    t.string   "configuration_file"
    t.string   "data_file_name"
    t.string   "data_set_full_name"
    t.string   "data_set_short_name"
    t.text     "data_set_citation"
    t.string   "unit_of_analysis"
    t.integer  "first_year_possible"
    t.integer  "last_year_possible"
    t.boolean  "label_line_in_data_file"
    t.integer  "number_of_variables"
    t.integer  "number_of_cases"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "identifierccode1_var"
    t.integer  "identifierccode2_var"
    t.integer  "identifieryear_var"
    t.text     "description"
    t.text     "description_fr"
    t.string   "data_set_short_name_fr"
  end

  create_table "diese_null", :id => false, :force => true do |t|
    t.integer "annee"
    t.integer "begin"
    t.integer "end"
    t.text    "ccode"
    t.string  "fips_cntry", :limit => 2
    t.integer "diese"
    t.integer "manquante"
  end

  create_table "dip_ex", :id => false, :force => true do |t|
    t.integer "ccode1"
    t.integer "ccode2"
    t.integer "year"
    t.integer "dr_at_1"
    t.integer "dr_at_2"
    t.integer "de"
    t.string  "version", :limit => nil
  end

  create_table "fips_cow_codes", :force => true do |t|
    t.string   "country_name"
    t.integer  "cowcode"
    t.string   "fips_cntry"
    t.integer  "contcode"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "var_labels", :force => true do |t|
    t.integer  "var_key"
    t.integer  "var_id"
    t.integer  "dataset_id"
    t.integer  "value"
    t.string   "meaning"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "meaning_fr"
    t.text     "description_fr"
  end

  create_table "variables", :force => true do |t|
    t.integer  "var_id"
    t.integer  "dataset_id"
    t.string   "name"
    t.string   "format"
    t.string   "kind"
    t.string   "reverse"
    t.string   "missing"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "mini"
    t.float    "maxi"
    t.integer  "binary_var"
    t.integer  "qualitatif_ordonne"
    t.string   "long_name"
    t.string   "code_var"
    t.text     "descr_before"
    t.text     "descr_after"
    t.string   "long_name_fr"
    t.text     "descr_before_fr"
    t.text     "descr_after_fr"
    t.integer  "page"
    t.string   "unit"
    t.string   "name_fr"
    t.string   "unit_fr"
  end

  add_index "variables", ["dataset_id", "var_id"], :name => "index_variables_on_var_id_and_dataset_id", :unique => true

  create_table "world", :id => false, :force => true do |t|
    t.integer "gid"
    t.string  "fips_cntry", :limit => 2
    t.string  "cntry_name", :limit => 40
    t.integer "begin"
    t.integer "end"
  end

  create_table "world3", :id => false, :force => true do |t|
    t.integer "cowcode"
    t.string  "fips_cntry", :limit => 2
    t.string  "cntry_name", :limit => 40
    t.integer "begin"
    t.integer "end"
    t.text    "ccode"
  end

end
