# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# Pour lancer Pgsql, sous Ubuntu:
# Menu Système/Administration/services/
# et Cocher "Serveur de base de données (postgresql-8.0)
# ouvrir http://127.0.0.1:3000/carte
# ou http://mayeul-kauffmann.fr.eu.org:3000/carte

# base de developpement habituelle: 'testsgis' au lieu
# de  'testsguy' (qui elle s'utilise en lançant le serveur
#  avec le mode "developmentguy")
development:
  adapter: postgresql
  database: prism_db
  username: postgres
  password: rootpg38000
  host: 192.168.1.18
  port: 5433


developmentguy:
  adapter: postgresql
  database: testsguy
  username: cartecurseurv1
  password: rootpg38000
  host: 192.168.1.18
  port: 5433


# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: peace_prism_test
  username: postgres
  password: rootpg38000
  host: 192.168.1.18
  port: 5433
  
#test:
#  adapter: sqlite
#  database: peace_prism_test
#  username: postgres
#  password: rootpg38000
#  host: 192.168.1.18
#  port: 5433
#  

production:
  adapter: postgresql
  database: prism_db
  username: postgres
  password: rootpg38000
  host: 192.168.1.18
  port: 5433
